# Generated by Django 5.0.2 on 2024-03-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_deliverydetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='mobile_no',
            field=models.CharField(max_length=20),
        ),
    ]
