# Generated by Django 5.0.2 on 2024-03-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_deliverydetails_mobile_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
