# Generated by Django 5.0.2 on 2024-03-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_successful',
            field=models.BooleanField(default=False),
        ),
    ]
