# Generated by Django 5.0.2 on 2024-04-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_order_order_id_cart_razor_pay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_successful',
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_successful',
            field=models.BooleanField(default=False),
        ),
    ]
